export const PATH_ROOT = '/board'
export const PATH_CONFIG = '/board/config'
export const PATH_ROWS = '/board/rows'
export const PATH_COLUMNS = '/board/columns'
export const PATH_ITEMS = '/board/items'
export const PATH_BOARD = '/board/board'
export const PATH_CONTAINER = '/board/containers'
